// TODO(#139): The oracle module currently uses a simple Ed25519 signature
// scheme with a single trusted pubkey stored per market. This needs to be
// replaced with a decentralised oracle integration (e.g. a Reflector or
// Pyth price-feed adapter) so that market resolution does not rely on a
// single off-chain signer. Tracked in:
// https://github.com/Vatix-Protocol/vatix-contract/issues/139

//! # Canonical Oracle Message Format
//!
//! The exact bytes the oracle must sign are:
//!
//! ```text
//! message = keccak256(market_id_be || outcome_byte)
//! ```
//!
//! | Field          | Encoding                          | Width  |
//! |----------------|-----------------------------------|--------|
//! | `market_id_be` | `u32` as **big-endian** bytes     | 4 bytes|
//! | `outcome_byte` | `0x01` = YES / `0x00` = NO        | 1 byte |
//!
//! **Backend alignment**: the backend signer MUST concatenate these raw bytes
//! and keccak256-hash the result. JSON canonicalization produces a different
//! message and will never verify on-chain. Use the shared test vector at
//! `test-vectors/oracle-message.json` (generated by `cargo test
//! export_oracle_test_vector`) to confirm your signing implementation produces
//! the expected `keccak_hex` before sending signatures to the contract.

use crate::error::ContractError;
use crate::types::{AdapterType, Market};
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use soroban_sdk::{Bytes, BytesN, Env};

/// Construct the message that the oracle signs.
///
/// Message format: `keccak256(market_id_be || outcome_byte)`
/// - `market_id`: u32 big-endian (4 bytes)
/// - `outcome_byte`: `0x01` = YES, `0x00` = NO
pub fn construct_oracle_message(env: &Env, market_id: u32, outcome: bool) -> BytesN<32> {
    let mut message = Bytes::new(env);
    message.append(&Bytes::from_slice(env, &market_id.to_be_bytes()));
    message.append(&Bytes::from_slice(env, &[u8::from(outcome)]));
    env.crypto().keccak256(&message).into()
}

/// Verify an ed25519 signature without panicking on invalid input.
///
/// `env.crypto().ed25519_verify` traps the host (an unrecoverable WASM trap,
/// not a catchable error) when the signature fails to verify, so it cannot
/// be used here — any failure must surface as a typed [`ContractError`].
/// Verification is therefore done in pure Rust via `ed25519-dalek`, which
/// reports failure as a `Result` instead of trapping.
///
/// Returns `false` if `pubkey` does not decode to a valid curve point or if
/// the signature does not verify against `message`.
fn verify_ed25519_safe(pubkey: &BytesN<32>, message: &BytesN<32>, signature: &BytesN<64>) -> bool {
    let Ok(verifying_key) = VerifyingKey::from_bytes(&pubkey.to_array()) else {
        return false;
    };
    let signature = Signature::from_bytes(&signature.to_array());
    verifying_key
        .verify(&message.to_array(), &signature)
        .is_ok()
}

/// Verify that an oracle signature is valid for a market resolution.
///
/// # Errors
/// - [`ContractError::UnauthorizedOracle`] if `oracle_pubkey` is the zero key.
/// - [`ContractError::InvalidSignature`] if the signature does not verify
///   against `construct_oracle_message(env, market_id, outcome)`.
///
/// # Security
/// Uses Ed25519 signature verification, performed in pure Rust (see
/// [`verify_ed25519_safe`]) rather than the host's `ed25519_verify`, so that
/// an invalid signature returns a typed error instead of trapping the host.
pub fn verify_oracle_signature(
    env: &Env,
    market_id: u32,
    outcome: bool,
    signature: &BytesN<64>,
    oracle_pubkey: &BytesN<32>,
) -> Result<(), ContractError> {
    if oracle_pubkey == &BytesN::from_array(env, &[0u8; 32]) {
        return Err(ContractError::UnauthorizedOracle);
    }

    let message = construct_oracle_message(env, market_id, outcome);
    if !verify_ed25519_safe(oracle_pubkey, &message, signature) {
        return Err(ContractError::InvalidSignature);
    }

    Ok(())
}

/// Check whether `oracle_pubkey` is authorised to resolve `market`.
///
/// MVP: pubkey must match `market.oracle_pubkey` exactly.
/// Post-MVP: could check against a registry of approved oracles.
///
/// # Errors
/// - [`ContractError::UnauthorizedOracle`] if the pubkey doesn't match.
#[allow(dead_code)]
pub fn validate_oracle_authorization(
    market: &Market,
    oracle_pubkey: &BytesN<32>,
) -> Result<(), ContractError> {
    if market.oracle_pubkey == *oracle_pubkey {
        Ok(())
    } else {
        Err(ContractError::UnauthorizedOracle)
    }
}

/// Verify that the market outcome is valid according to the configured oracle adapter.
///
/// For `AdapterType::Ed25519`, this verifies the provided signature against the
/// market's `oracle_pubkey`. Other adapter types are not yet implemented and
/// currently return `UnauthorizedOracle` to prevent accidental silent success.
pub fn verify_market_outcome(
    env: &Env,
    market_id: u32,
    market: &Market,
    adapter_type: AdapterType,
    outcome: bool,
    proof: &BytesN<64>,
) -> Result<(), ContractError> {
    match adapter_type {
        AdapterType::Ed25519 => verify_oracle_signature(env, market_id, outcome, proof, &market.oracle_pubkey),
        AdapterType::Reflector | AdapterType::Pyth => Err(ContractError::UnauthorizedOracle),
    }
}

#[cfg(test)]
mod tests {
    extern crate std;
    use std::format;
    use super::*;
    use crate::types::MarketStatus;
    use soroban_sdk::{
        testutils::{Address as _, BytesN as _},
        Address, Env, String,
    };

    fn make_market(env: &Env, oracle_pubkey: BytesN<32>) -> Market {
        Market {
            id: 1,
            question: String::from_str(env, "Test market"),
            end_time: 1000,
            oracle_pubkey,
            status: MarketStatus::Active,
            result: None,
            creator: Address::generate(env),
            created_at: 0,
            collateral_token: Address::generate(env),
            price_bps: 5_000,
            resolver: None,
            resolved_at: None,
            adapter_type: AdapterType::Ed25519,
        }
    }

    #[test]
    fn test_construct_oracle_message_yes() {
        let env = Env::default();
        let message = construct_oracle_message(&env, 1u32, true);
        assert_eq!(message.len(), 32);
    }

    #[test]
    fn test_construct_oracle_message_no() {
        let env = Env::default();
        let message = construct_oracle_message(&env, 1u32, false);
        assert_eq!(message.len(), 32);
    }

    #[test]
    fn test_different_outcomes_different_messages() {
        let env = Env::default();
        let msg_yes = construct_oracle_message(&env, 1u32, true);
        let msg_no = construct_oracle_message(&env, 1u32, false);
        assert_ne!(msg_yes, msg_no);
    }

    #[test]
    fn test_construct_oracle_message_deterministic() {
        let env = Env::default();
        let msg1 = construct_oracle_message(&env, 456u32, true);
        let msg2 = construct_oracle_message(&env, 456u32, true);
        assert_eq!(msg1, msg2);
    }

    #[test]
    fn test_different_market_ids_different_messages() {
        let env = Env::default();
        let msg1 = construct_oracle_message(&env, 1u32, true);
        let msg2 = construct_oracle_message(&env, 2u32, true);
        assert_ne!(msg1, msg2);
    }

    #[test]
    fn test_construct_oracle_message_zero_id() {
        let env = Env::default();
        let message = construct_oracle_message(&env, 0u32, true);
        assert_eq!(message.len(), 32);
    }

    #[test]
    fn test_construct_oracle_message_large_id() {
        let env = Env::default();
        let message = construct_oracle_message(&env, u32::MAX, false);
        assert_eq!(message.len(), 32);
    }

    #[test]
    fn test_construct_oracle_message_various_ids() {
        let env = Env::default();
        let msg1 = construct_oracle_message(&env, 100u32, true);
        let msg2 = construct_oracle_message(&env, 1000u32, true);
        let msg3 = construct_oracle_message(&env, 10000u32, true);
        assert_ne!(msg1, msg2);
        assert_ne!(msg2, msg3);
        assert_ne!(msg1, msg3);
        assert_eq!(msg1.len(), 32);
    }

    #[test]
    fn test_validate_oracle_authorized() {
        let env = Env::default();
        let oracle_pubkey = BytesN::from_array(&env, &[1u8; 32]);
        let market = make_market(&env, oracle_pubkey.clone());
        assert!(validate_oracle_authorization(&market, &oracle_pubkey).is_ok());
    }

    #[test]
    fn test_validate_oracle_authorization_zero_pubkey() {
        let env = Env::default();
        let zero_pubkey = BytesN::from_array(&env, &[0u8; 32]);
        let market = make_market(&env, BytesN::from_array(&env, &[1u8; 32]));
        let result = validate_oracle_authorization(&market, &zero_pubkey);
        assert_eq!(result, Err(ContractError::UnauthorizedOracle));
    }

    #[test]
    fn test_validate_oracle_unauthorized() {
        let env = Env::default();
        let market = make_market(&env, BytesN::from_array(&env, &[1u8; 32]));
        let wrong_pubkey = BytesN::from_array(&env, &[2u8; 32]);
        let result = validate_oracle_authorization(&market, &wrong_pubkey);
        assert_eq!(result, Err(ContractError::UnauthorizedOracle));
    }

    #[test]
    fn test_verify_signature_rejects_zero_pubkey() {
        let env = Env::default();
        let result = verify_oracle_signature(
            &env,
            1u32,
            true,
            &BytesN::from_array(&env, &[0u8; 64]),
            &BytesN::from_array(&env, &[0u8; 32]),
        );
        assert_eq!(result, Err(ContractError::UnauthorizedOracle));
    }

    #[test]
    fn test_verify_invalid_signature() {
        let env = Env::default();
        let result = verify_oracle_signature(
            &env,
            123u32,
            true,
            &BytesN::random(&env),
            &BytesN::random(&env),
        );
        assert_eq!(result, Err(ContractError::InvalidSignature));
    }

    /// Generate an ed25519 keypair and sign `construct_oracle_message(market_id, outcome)`.
    fn generate_keypair_and_sign(
        env: &Env,
        market_id: u32,
        outcome: bool,
    ) -> (BytesN<32>, BytesN<64>) {
        use ed25519_dalek::{Signer, SigningKey};
        use rand::rngs::OsRng;

        let signing_key = SigningKey::generate(&mut OsRng);
        let message = construct_oracle_message(env, market_id, outcome);
        let signature = signing_key.sign(message.to_array().as_slice());

        (
            BytesN::from_array(env, &signing_key.verifying_key().to_bytes()),
            BytesN::from_array(env, &signature.to_bytes()),
        )
    }

    #[test]
    fn test_verify_valid_signature_succeeds() {
        let env = Env::default();
        let market_id = 1u32;
        let outcome = true;
        let (pubkey, signature) = generate_keypair_and_sign(&env, market_id, outcome);

        let result = verify_oracle_signature(&env, market_id, outcome, &signature, &pubkey);
        assert_eq!(result, Ok(()));
    }

    #[test]
    fn test_verify_signature_wrong_outcome_fails() {
        let env = Env::default();
        let market_id = 1u32;
        let (pubkey, signature) = generate_keypair_and_sign(&env, market_id, true);

        // Signature was produced for outcome=true; verifying against false must fail.
        let result = verify_oracle_signature(&env, market_id, false, &signature, &pubkey);
        assert_eq!(result, Err(ContractError::InvalidSignature));
    }

    #[test]
    fn test_verify_signature_wrong_market_id_fails() {
        let env = Env::default();
        let outcome = true;
        let (pubkey, signature) = generate_keypair_and_sign(&env, 1u32, outcome);

        // Signature was produced for market_id=1; verifying against 2 must fail.
        let result = verify_oracle_signature(&env, 2u32, outcome, &signature, &pubkey);
        assert_eq!(result, Err(ContractError::InvalidSignature));
    }

    #[test]
    fn test_verify_signature_from_different_keypair_fails() {
        let env = Env::default();
        let market_id = 1u32;
        let outcome = true;
        let (_pubkey, signature) = generate_keypair_and_sign(&env, market_id, outcome);
        let (other_pubkey, _other_signature) = generate_keypair_and_sign(&env, market_id, outcome);

        // Signature was produced by a different keypair than `other_pubkey`.
        let result = verify_oracle_signature(&env, market_id, outcome, &signature, &other_pubkey);
        assert_eq!(result, Err(ContractError::InvalidSignature));
    }

    /// Export a deterministic test vector so the backend signer can validate
    /// its keccak256 + Ed25519 implementation against the on-chain format.
    ///
    /// Writes `test-vectors/oracle-message.json` at the workspace root.
    /// Run with `cargo test export_oracle_test_vector -- --nocapture`.
    #[test]
    fn export_oracle_test_vector() {
        use ed25519_dalek::{Signer, SigningKey};

        // Fixed seed — deterministic across runs so the vector is stable.
        let seed = [0x42u8; 32];
        let signing_key = SigningKey::from_bytes(&seed);
        let verifying_key = signing_key.verifying_key();

        let env = Env::default();
        let market_id: u32 = 1;
        let outcome = true; // YES

        let message = construct_oracle_message(&env, market_id, outcome);
        let message_bytes = message.to_array();
        let signature = signing_key.sign(&message_bytes);

        // Verify the vector is self-consistent before writing.
        assert!(
            verify_oracle_signature(
                &env,
                market_id,
                outcome,
                &BytesN::from_array(&env, &signature.to_bytes()),
                &BytesN::from_array(&env, &verifying_key.to_bytes()),
            )
            .is_ok(),
            "test vector signature must verify on-chain"
        );

        let to_hex = |b: &[u8]| -> std::string::String { b.iter().map(|x| format!("{:02x}", x)).collect() };

        let mut raw = [0u8; 5];
        raw[..4].copy_from_slice(&market_id.to_be_bytes());
        raw[4] = u8::from(outcome);

        let json = format!(
            concat!(
                "{{\n",
                "  \"description\": \"Canonical oracle message: keccak256(market_id_be || outcome_byte)\",\n",
                "  \"market_id\": {market_id},\n",
                "  \"outcome\": \"YES\",\n",
                "  \"raw_hex\": \"{raw_hex}\",\n",
                "  \"keccak_hex\": \"{keccak_hex}\",\n",
                "  \"pubkey_hex\": \"{pubkey_hex}\",\n",
                "  \"signature_hex\": \"{sig_hex}\"\n",
                "}}\n"
            ),
            market_id = market_id,
            raw_hex = to_hex(&raw),
            keccak_hex = to_hex(&message_bytes),
            pubkey_hex = to_hex(&verifying_key.to_bytes()),
            sig_hex = to_hex(&signature.to_bytes()),
        );

        let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/../../test-vectors");
        let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../test-vectors/oracle-message.json");
        std::fs::create_dir_all(dir).expect("create test-vectors dir");
        std::fs::write(path, &json).expect("write oracle-message.json");
    }
}
